web/router.ex
defmodule Flog.Router do
  use Flog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Flog.Auth, repo: Flog.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Flog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/users/new", UserController, :new
    post "/users", UserController, :create
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/portfolio", PortfolioController, :index
    get "/bio", BioController, :index
  end

  scope "/flog", Flog do
    pipe_through [:browser, :authenticate_user]

    get "/users", UserController, :index
    delete "/users/:id", UserController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Flog do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Flog.LayoutView do
  use Flog.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>resurgens.io</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great|Special+Elite" rel="stylesheet">
  </head>

  <body class="bg-repeatable">
    <header class="header bg-header">
      <nav role="navigation">
        <ol class="breadcrumb pull-right typewriter">
          <!-- <li><button href="#" class="btn-lg menu-drop"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></button></li> -->
          <li><span class="glyphicon glyphicon-home"></span> <%= link "Home", to: page_path(@conn, :index) %></li>
          <li><span class="glyphicon glyphicon-fire"></span> Flog</li>
          <li><span class="glyphicon glyphicon-list-alt"></span> <%= link "Bio", to: bio_path(@conn, :index) %></li>
          <li><span class="glyphicon glyphicon-book"></span> <%= link "Portfolio", to: portfolio_path(@conn, :index) %></li>
          <%= if @current_user do %>
            <li><span class="glyphicon glyphicon-log-out"></span> <%= link "Logout", to: session_path(@conn, :delete, @current_user), method: :delete %></li>
            <li class="dropdown">
              <button type="button" id="user-dd" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="border: 0; background: transparent;">
                <span class="glyphicon glyphicon-user"></span> <%= @current_user.username %> <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="user-dd">
                <li role="separator" class="divider"></li>
                <li><%= link "All Users", to: user_path(@conn, :index) %></li>
              </ul>
            </li>
          <%= else %>
            <li><span class="glyphicon glyphicon-log-in"></span> <%= link "Login", to: session_path(@conn, :new) %></li>
          <% end %>
        </ol>
      </nav>
      <span class="logo"><span class="typewriter text-center"><h1><a href="/" style="color: black;">resurgens.io</a></h1></span></span>
      <div class="bg-sep">

      </div>
    </header>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    </div>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <br><br>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </body>
</html>